#!/usr/bin/env bash

# TODO (Run this script as): color magenta && echo hello && color reset

color() {
    echo -ne "\033[$1;$2m"
}

declare -A color_mapping=(
    # TODO: Add more color values
    # Refer bash color codes
    [magenta]=35
    [black]=30
    [red]=31
    [green]=32
    [yellow]=33
    [blue]=34
    [cyan]=36
    [white]=37
    [bright_black]=90
    [bright_red]=91
    [bright_green]=92
    [bright_yellow]=93
    [bright_blue]=94
    [bright_magenta]=95
    [bright_cyan]=96
    [bright_white]=97

)

if [[ $1 == 'reset' ]]; then
    echo -ne "\033[0m"
else
    color 1 ${color_mapping[$1]}
fi